add_flight:
    path: /airport/api/flight
    methods: POST
    controller: App\Controller\Airport\AirportController::addFlight

add_passenger:
    path: /airport/api/passenger
    methods: POST
    controller: App\Controller\Airport\AirportController::addPassenger

add_ticket:
    path: /airport/api/ticket
    methods: POST
    controller: App\Controller\Airport\AirportController::addTicket

find_tickets_by_passenger_name:
    path: /airport/api/tickets/{name}
    methods: GET
    controller: App\Controller\Airport\AirportController::findTicketsByPassengerName

get_amount_of_tickets_for_flight:
    path: /airport/api/tickets/amount/{flight_id}
    methods: GET
    controller: App\Controller\Airport\AirportController::getAmountOfTicketsForFlight
    requirements:
        flight_id: '\d+'

app.swagger_ui:
    path: /airport/api/docs
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
